<?php
# This file was generated by pymediawikidocker {{pmwdVersion}} at {{timestamp}}
# see http://wiki.bitplan.com/index.php/Pymediawikidocker
#
# https://www.php.net/manual/en/function.phpinfo.php
#  Outputs information about PHP's configuration
phpinfo();


?>
