#!/bin/bash
# WF 2020-07-27
pip --version
pip install .

# make sure pywikibot configuration is available
if [ ! -d $HOME/.pywikibot ]
then
   mkdir $HOME/.pywikibot
   echo "creating user-config.py"
   echo "put_throttle = 0" > $HOME/.pywikibot/user-config.py
fi
